version: "3.8"

services:
  inloopid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inloopid_ubuntu_container
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
