#!/data/data/com.termux/files/usr/bin/bash

set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"

PROJECT="InLoopID"

DOCS="$ROOT/$PROJECT/docs"

BUILD="$ROOT/$PROJECT/build"

OUTPUT="$ROOT/$PROJECT/output"

LOGS="$ROOT/$PROJECT/logs"

PYTHON="$ROOT/$PROJECT/python"

SCRIPTS="$ROOT/$PROJECT/scripts"

CONFIG="$ROOT/$PROJECT/config"

CSV="$ROOT/$PROJECT/chapters.csv"

SUMMARY="$DOCS/SUMMARY.md"

MKDOCS="$ROOT/$PROJECT/mkdocs.yml"

README="$ROOT/$PROJECT/README.md"

VERSION="0.1.0"

DATE=$(date "+%Y-%m-%d %H:%M:%S")

GREEN="\033[32m"
BLUE="\033[34m"
RED="\033[31m"
YELLOW="\033[33m"
NC="\033[0m"

banner(){

echo

echo "=============================================================="

echo "            InLoopID Enterprise Documentation"

echo "=============================================================="

echo

echo "Version : $VERSION"

echo "Generated : $DATE"

echo

}

info(){

echo -e "${BLUE}[INFO]${NC} $1"

}

ok(){

echo -e "${GREEN}[ OK ]${NC} $1"

}

warn(){

echo -e "${YELLOW}[WARN]${NC} $1"

}

fail(){

echo -e "${RED}[FAIL]${NC} $1"

exit 1

}

prepare(){

info "Creating folders..."

mkdir -p "$DOCS"

mkdir -p "$BUILD"

mkdir -p "$OUTPUT"

mkdir -p "$LOGS"

mkdir -p "$DOCS/generated"

mkdir -p "$DOCS/templates"

mkdir -p "$DOCS/api"

mkdir -p "$DOCS/security"

mkdir -p "$DOCS/business"

mkdir -p "$DOCS/devops"

mkdir -p "$DOCS/testing"

mkdir -p "$DOCS/reference"

mkdir -p "$DOCS/uml"

mkdir -p "$DOCS/c4"

mkdir -p "$DOCS/bpmn"

mkdir -p "$DOCS/openapi"

mkdir -p "$DOCS/adr"

ok "Folders ready."

}

create_index(){

info "Generating index..."

cat > "$DOCS/index.md" <<EOF
# InLoopID Enterprise Documentation

---

Welcome.

Documentation generated automatically.

---

## Sections

- Executive
- Business
- Product
- Architecture
- Security
- GDPR
- Integrations
- API
- UX
- DevOps
- Finance
- Support

---

Generated:

$DATE

EOF

ok "index.md"

}

create_summary(){

info "Creating SUMMARY..."

echo "# Documentation" > "$SUMMARY"

echo "" >> "$SUMMARY"

}

process_csv(){

[ -f "$CSV" ] || fail "Missing chapters.csv"

CURRENT=""

while IFS=',' read -r NUMBER CATEGORY TITLE

do

[ -z "$NUMBER" ] && continue

DIR="$DOCS/$CATEGORY"

mkdir -p "$DIR"

FILE="$DIR/$NUMBER.md"

if [ ! -f "$FILE" ]; then

cat > "$FILE" <<EOF
# $TITLE

---

Status: Draft

---

## Overview

TODO

---

## Purpose

TODO

---

## Description

TODO

---

## Architecture

TODO

---

## Security

TODO

---

## Examples

TODO

---

## References

TODO

EOF

fi

if [ "$CURRENT" != "$CATEGORY" ]; then

echo "" >> "$SUMMARY"

echo "## $CATEGORY" >> "$SUMMARY"

echo "" >> "$SUMMARY"

CURRENT="$CATEGORY"

fi

echo "- [$NUMBER $TITLE]($CATEGORY/$NUMBER.md)" >> "$SUMMARY"

done < "$CSV"

ok "Markdown generated."

}

generate_readme(){

info "Updating README..."

cat > "$README" <<EOF
# InLoopID Enterprise Documentation

Generated by Enterprise Generator.

Version:

$VERSION

Generated:

$DATE

EOF

ok "README"

}

generate_mkdocs(){

info "Generating mkdocs.yml..."

cat > "$MKDOCS" <<EOF
site_name: InLoopID Enterprise Documentation

theme:

  name: material

docs_dir: docs

plugins:

  - search

markdown_extensions:

  - admonition

  - tables

  - toc

nav:

  - Home: index.md

  - Documentation: SUMMARY.md

EOF

ok "mkdocs.yml"

}

statistics(){

TOTAL=$(find "$DOCS" -name "*.md" | wc -l)

echo

echo "--------------------------------"

echo "Markdown files : $TOTAL"

echo "Output folder  : $OUTPUT"

echo "Documentation  : $DOCS"

echo "--------------------------------"

}

finish(){

echo

echo "Done."

echo

echo "Next steps"

echo

echo "pip install -r requirements.txt"

echo

echo "cd $PROJECT"

echo

echo "mkdocs serve"

echo

echo "http://127.0.0.1:8000"

echo

}

main(){

banner

prepare

create_index

create_summary

process_csv

generate_readme

generate_mkdocs

statistics

finish

}

main "$@"

